name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

# ДОБАВЬТЕ ЭТИ ПРАВА!
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pelican markdown

    - name: Build site
      run: pelican content -s publishconf.py

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Оставьте этот токен!
        publish_dir: ./output